'use client';
import { useEffect, useRef, useState, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { ArrowUpRight, MapPin, RefreshCw, Check, SlidersHorizontal, X, Search, Leaf, BriefcaseBusiness } from 'lucide-react';
import './opportunities.css';
type Analysis = {score:number; rawScore:number; category:string; verdict:string; summary:string; positives:string[]; negatives:string[]; alerts:string[]; categories:string[]; parts:Record<string,number>; weights:Record<string,number>; geo:{city:string;department:string|null}; employer:{kind:string}; evidence:{energy:string[];missions:string[]}; days:number|null; recommended:boolean; needsReview:boolean;method:string};
type Job = {id:string;title:string;company:string;location:string;url:string;description?:string;postedAt?:string|number;fetchedAt:string;lastVerifiedAt:string;source:string;contract?:string;workMode?:string;salary?:{min?:number;max?:number;currency?:string};status:string;analysis:Analysis;alternatives?:{url:string;source:string}[];semanticError?:string};
type Data = {jobs:Job[];aiAvailable:boolean;lastRun:null|{finishedAt:string;status:string;sources:{name:string;status:string;fetched:number;inZone?:number;described?:number;message?:string;coverage?:string}[]}};
const categories=['Énergie','Efficacité énergétique','Performance énergétique','Méthodes','Amélioration continue','Performance industrielle'];
const statuses=['Nouveau','À analyser','Intéressant','À postuler','Candidature envoyée','Entretien','Refus','Archivé'];
const dimensions:Record<string,string>={domain:'Domaine métier',missions:'Missions réelles',employer:'Employeur final',location:'Localisation',quality:'Qualité de l’offre'};
const date=(value?:string|number)=>value&&Number.isFinite(new Date(value).getTime())?new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'}):'Date non renseignée';
const salary=(s:Job['salary'])=>s?[s.min,s.max].filter(v=>v!=null).map(v=>v!.toLocaleString('fr-FR')).join(' – ')+' '+(s.currency||'')+'/an':null;
export function OpportunitiesView(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[department,setDepartment]=useState(''),[sort,setSort]=useState('score'),[view,setView]=useState('recommended'),[selected,setSelected]=useState<Job|null>(null),[saving,setSaving]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let active=true;fetch('/api/opportunities').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/opportunities',{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function changeStatus(job:Job,status:string){setSaving(true);setError('');try{const r=await fetch('/api/opportunities',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:job.id,status})});if(!r.ok)throw Error('Le statut n’a pas été enregistré.');setData(d=>d?{...d,jobs:d.jobs.map(j=>j.id===job.id?{...j,status}:j)}:d);setSelected(j=>j?.id===job.id?{...j,status}:j);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 const jobs=useMemo(()=>{
  const search=query.toLocaleLowerCase('fr');
  return (data?.jobs||[]).filter(j=>{
   const a=j.analysis;
   const inView=view==='recommended'?a.recommended&&j.status!=='Archivé':view==='review'?a.needsReview&&a.category!=='REJETÉE':view==='saved'?['Intéressant','À postuler','Candidature envoyée','Entretien'].includes(j.status):view==='archived'?j.status==='Archivé':a.category==='REJETÉE'||!a.recommended&&!a.needsReview;
   return inView&&(!category||a.categories.includes(category))&&(!department||a.geo.department===department)&&(!search||`${j.title} ${j.company} ${j.location}`.toLocaleLowerCase('fr').includes(search));
  }).sort((a,b)=>sort==='date'?(new Date(b.postedAt||0).getTime()-new Date(a.postedAt||0).getTime()):sort==='company'?a.company.localeCompare(b.company,'fr'):sort==='location'?a.location.localeCompare(b.location,'fr'):b.analysis.score-a.analysis.score||(new Date(b.postedAt||0).getTime()-new Date(a.postedAt||0).getTime()));
 },[data,query,category,department,sort,view]);
 const recommended=data?.jobs.filter(j=>j.analysis.recommended&&j.status!=='Archivé').length||0;
 const reviews=data?.jobs.filter(j=>j.analysis.needsReview&&j.analysis.category!=='REJETÉE').length||0;
 return <div className="opportunities">
  <section className="op-hero"><div><div className="op-eyebrow"><span/> VOTRE RECHERCHE, PLUS CIBLÉE</div><h1>Votre prochain poste<br/><em>dans l’énergie.</em></h1><p>Les bonnes missions. Chez l’employeur final.<br/>Paris et petite couronne, exclusivement.</p><div className="op-zone"><MapPin size={15}/> Paris · Hauts-de-Seine · Seine-Saint-Denis · Val-de-Marne</div></div><div className="op-summary"><Leaf size={26}/><strong>{recommended}</strong><span>opportunités recommandées</span><small>{data?.lastRun?'Actualisé le '+date(data.lastRun.finishedAt):'Lancez votre première recherche'}</small><Button onClick={refresh} disabled={busy}><RefreshCw size={15} className={busy?'op-spin':''}/>{busy?'Recherche en cours…':'Actualiser les offres'}</Button></div></section>
  {error&&<div role="alert" className="op-alert">{error}</div>}
  {data?.lastRun?.status==='error'&&<div role="alert" className="op-alert">Les sources sont actuellement inaccessibles. Les résultats précédents sont conservés ; consultez le détail des sources ci-dessous.</div>}
  <div className="op-content"><div className="op-section-head"><div><div className="op-eyebrow">VOTRE SÉLECTION</div><h2>Offres recommandées</h2></div><span className="op-subtle">Triées selon vos critères · score sur 100</span></div>
   <div className="op-tabs" role="group" aria-label="Vue des offres">{[['recommended','Recommandées',recommended],['review','À vérifier',reviews],['saved','Mon suivi',null],['rejected','Écartées',null],['archived','Archives',null]].map(([value,label,count])=><button key={value} onClick={()=>setView(String(value))} aria-pressed={view===value} className={view===value?'active':''}>{label}{count!==null&&<span>{count}</span>}</button>)}</div>
   <div className="op-toolbar"><label className="op-search"><Search size={17}/><input aria-label="Rechercher une offre" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Intitulé, entreprise, ville…"/></label><label><span className="sr-only">Département</span><select aria-label="Département" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Toute la zone</option>{['75','92','93','94'].map(d=><option key={d}>{d}</option>)}</select></label><label><span className="sr-only">Trier par</span><select aria-label="Trier par" value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Pertinence</option><option value="date">Publication récente</option><option value="location">Localisation</option><option value="company">Entreprise</option></select></label></div>
   <div className="op-filters"><SlidersHorizontal size={15}/><button className={!category?'active':''} onClick={()=>setCategory('')}>Tous les domaines</button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(category===c?'':c)}>{c}</button>)}</div>
   <div aria-live="polite" className="op-result-count">{data?`${jobs.length} offre${jobs.length>1?'s':''} dans cette vue`:'Chargement des offres…'}{busy&&' · Collecte et analyse en cours, cela peut prendre quelques minutes.'}</div>
   <div className="op-list">{jobs.slice(0,100).map(job=><article className="op-card" key={job.id}>
    <div className={'op-score '+(job.analysis.score>=85?'excellent':'')}><strong>{job.analysis.score}</strong><span>/ 100</span></div><div className="op-card-main"><div className="op-card-top"><span className="op-category">{job.analysis.category}</span><span className="op-subtle">{date(job.postedAt)}</span></div><button className="op-title" onClick={()=>setSelected(job)}>{job.title}</button><div className="op-meta"><strong>{job.company}</strong><span><MapPin size={13}/>{job.analysis.geo.city||job.location}{job.analysis.geo.department&&' · '+job.analysis.geo.department}</span>{job.contract&&<span>{job.contract}</span>}{job.workMode&&<span>{job.workMode}</span>}{salary(job.salary)&&<span>{salary(job.salary)}</span>}</div><p className="op-reason">{job.analysis.summary}</p><div className="op-checks">{job.analysis.positives.slice(0,4).map(p=><span key={p}><Check size={13}/>{p}</span>)}</div><div className="op-card-bottom"><span className={job.analysis.verdict==='POSTULER'?'op-verdict':'op-subtle'}>{job.analysis.verdict}</span><span className="op-subtle">{job.status}</span><a href={job.url} target="_blank" rel="noopener noreferrer">Offre originale <ArrowUpRight size={15}/></a><button onClick={()=>setSelected(job)}>Voir l’analyse <ArrowUpRight size={15}/></button></div></div>
   </article>)}</div>
   {data&&jobs.length===0&&<div className="op-empty"><BriefcaseBusiness size={32}/><h3>{data.lastRun?'Aucune offre dans cette sélection':'Votre sélection commence ici'}</h3><p>{data.lastRun?'Essayez un autre filtre ou consultez les offres à vérifier. La couverture actuelle se limite aux sources indiquées ci-dessous.':'Actualisez les offres pour rechercher des opportunités réelles auprès des employeurs configurés.'}</p>{!data.lastRun&&<Button onClick={refresh} disabled={busy}>Rechercher des offres</Button>}</div>}
   {jobs.length>100&&<p>Les 100 premières offres sont affichées. Affinez les filtres pour parcourir la sélection.</p>}
   <details className="op-sources"><summary>Sources et fonctionnement</summary><p>Collecte par les providers Career-Ops. Actualisation au maximum toutes les 12 heures. Les échecs et descriptions manquantes sont signalés ; la couverture n’est pas exhaustive.</p>{data?.lastRun?.sources.map(s=><p key={s.name}><strong>{s.name}</strong> — {s.status==='ok'?`${s.fetched} offres récupérées · ${s.inZone} dans la zone · ${s.described} descriptions · ${s.coverage}`:'Source indisponible : '+s.message}</p>)}<p>{data?.aiAvailable?'Analyse IA activée avec preuves textuelles.':'Analyse par règles contextuelles. L’analyse IA optionnelle n’est pas activée.'} Le score mesure votre ciblage professionnel ; votre expérience et vos diplômes n’ont pas encore été renseignés.</p><p>Une date inconnue reste inconnue. La présence dans le flux employeur est une vérification de disponibilité via API ; l’état de la page originale peut évoluer.</p></details>
  </div>
  <dialog ref={dialog} className="op-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}} aria-labelledby="op-detail-title">{selected&&<div className="op-detail"><button className="op-close" aria-label="Fermer l’analyse" onClick={()=>setSelected(null)}><X/></button><span className="op-eyebrow">ANALYSE DE L’OFFRE</span><h2 id="op-detail-title">{selected.title}</h2><p>{selected.company} · {selected.location}</p><div className="op-detail-score"><strong>{selected.analysis.score}<small>/100</small></strong><div><b>{selected.analysis.verdict}</b><p>{selected.analysis.category}</p></div></div><p>{selected.analysis.summary}</p><div className="op-detail-actions"><a href={selected.url} target="_blank" rel="noopener noreferrer">Ouvrir l’offre originale <ArrowUpRight size={17}/></a><label>Mon suivi<select aria-label="Statut de l’offre" value={selected.status} disabled={saving} onChange={e=>changeStatus(selected,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div><h3>Correspondance avec vos critères</h3>{Object.entries(selected.analysis.parts).map(([k,v])=><div className="op-dimension" key={k}><span>{dimensions[k]}</span><progress max={selected.analysis.weights[k]} value={v}/><b>{v}/{selected.analysis.weights[k]}</b></div>)}{selected.analysis.rawScore!==selected.analysis.score&&<p className="op-subtle">Score plafonné ou annulé en raison des vérifications ou exclusions ci-dessous.</p>}<h3>Points positifs</h3><ul>{selected.analysis.positives.map(p=><li key={p}>{p}</li>)}</ul><h3>Points négatifs et signaux d’alerte</h3><ul>{[...selected.analysis.negatives,...selected.analysis.alerts,...(selected.semanticError?[selected.semanticError]:[])].map(p=><li key={p}>{p}</li>)}</ul>{!selected.analysis.negatives.length&&!selected.analysis.alerts.length&&<p>Aucun signal bloquant détecté dans les informations disponibles.</p>}<h3>Éléments du descriptif</h3>{selected.analysis.evidence.energy.map((p,i)=><blockquote key={i}>{p}</blockquote>)}<h3>Description de l’offre</h3><p className="op-description">{selected.description||'Description complète indisponible. Consultez la source pour la vérifier.'}</p><div className="op-subtle">Publication : {date(selected.postedAt)} · Récupération : {date(selected.fetchedAt)} · Dernière vérification API : {date(selected.lastVerifiedAt)} · {selected.analysis.method}</div>{!!selected.alternatives?.length&&<p>Autres sources : {selected.alternatives.map(a=><a key={a.url} href={a.url} target="_blank" rel="noopener noreferrer">{a.source} </a>)}</p>}</div>}</dialog>
 </div>;
}
