import { asciiFold } from '../ascii-fold.mjs';
import { locate } from './geo.mjs';
export const VERSION = 'energy-1';
const fold = x => asciiFold(x || '');
const evidence = (text,re) => text.split(/(?<=[.!?;])\s+|\n/).filter(s=>re.test(fold(s))).map(s=>s.trim()).filter(Boolean).slice(0,4);
const energy = /\b(energi\w*|energy|energies|iso 50001|utilites|utilities|consommations? energetiques?|gtb|gtc|recuperation de chaleur)\b/;
const concrete = /\b(iso 50001|comptage|consommations?|kpi|indicateurs?|audit\w* energet\w*|cvc|utilites|utilities|gtb|gtc|vapeur|air comprime|chaleur|froid|chaud|electricite|energy efficiency|energy performance)\b/;
const action = /\b(analys\w*|optimis\w*|optimiz\w*|amelior\w*|reduc\w*|pilot\w*|suivi|monitor\w*|management|gerer|gestion|mesur\w*|audit\w*|projets?|plans? d action|indicateurs?|kpi)\b/;
const intermediaries = /\b(cabinet de (conseil|recrutement)|agence de (recrutement|travail temporaire)|societe de conseil|recruitment agency|staffing agency|consulting firm|chasseur de tetes|recrutons pour (notre|un) client|recrutement pour (notre|un) client|pour le compte de (notre|un) client)\b/;
const multiClient = /\b(missions? (chez|pour|aupres de) (nos|plusieurs|differents) clients|missions? clients|interven\w* chez (nos|plusieurs|differents) clients|accompagn\w* nos clients)\b/;
const consultant = /\b(consultant\w*|consulting)\b/;
const internal = /\b(equipe interne|direction (interne|energie)|nos (sites|usines|batiments|installations)|notre (site|usine|parc)|en interne|internal team|our (sites|plants))\b/;
export const CATEGORY_LABELS = ['Énergie','Efficacité énergétique','Performance énergétique','Méthodes','Amélioration continue','Performance industrielle'];
export function employer(job, config) {
 const title = fold(job.title), company = fold(job.company), body = fold(`${job.employerDescription||''}\n${job.description||''}`);
 const known = (config.excludedCompanies||[]).some(n=>company===fold(n));
 const agency = intermediaries.test(body) || intermediaries.test(company);
 const consultantTitle = consultant.test(title);
 const rotating = multiClient.test(body) && (consultantTitle || /\b(conseil|consulting|consultants?|missions?)\b/.test(body));
 if(known || agency || rotating || (consultantTitle && !internal.test(body))) return {kind:'intermediary',confirmed:true,reason:agency?'Cabinet de recrutement ou de conseil identifié':rotating?'Missions de conseil auprès de clients': 'Poste ou employeur de conseil identifié'};
 const direct = (config.directEmployers||[]).some(n=>company===fold(n)) || (internal.test(body) && !consultantTitle && !multiClient.test(body));
 if(direct) return {kind:'direct',confirmed:true,reason:'Employeur final : fonction interne ou exploitation opérationnelle'};
 return {kind:'unknown',confirmed:false,reason:'Nature de l’employeur à vérifier'};
}
export function category(score,rejected=false){return rejected?'REJETÉE':score>=85?'EXCELLENTE CIBLE':score>=70?'BONNE CIBLE':score>=55?'À ÉTUDIER':'FAIBLE PERTINENCE';}
export function analyze(job,config,now=Date.now()) {
 const geo=locate(job,config.departments);
 let org=employer(job,config);
 if(job.semantic?.employer==='intermediary')org={kind:'intermediary',confirmed:true,reason:'Intermédiaire identifié par analyse des missions'};
 else if(org.kind==='unknown'&&job.semantic?.employer==='direct')org={kind:'direct',confirmed:true,reason:'Employeur final étayé par le descriptif'};
 const description=job.missionsDescription || job.description || '';
 const title=fold(job.title), text=fold(description), missionEvidence=evidence(description,action);
 const energyEvidence=evidence(description,energy);
 const hasEnergy=energy.test(text), specific=concrete.test(text);
 const substantive=description.trim().length>=180;
 const technical= /\b(ingenieur|engineer|responsable|manager|chef de projet|charge de (mission|projet)|expert|methodes|performance|amelioration|optimis\w*|optimiz\w*)\b/.test(title);
 const linked = description.split(/(?<=[.!?;])\s+|\n/).filter(s=>energy.test(fold(s)) && action.test(fold(s)) && !/\b(experience|candidate|candidat|profil|atout|desirable)\b/.test(fold(s)));
 const engineering = technical && !/\b(technicien|agent|operateur|technician|operator)\b/.test(title);
 const relevant = substantive && (job.semantic?.relevant === true || (hasEnergy && (specific || energy.test(title)) && linked.length > 0 && engineering));
 const sales=/\b(commercial|business developer|sales|account executive|recruteur|recruiter|talent acquisition)\b/.test(title) && !/\b(technico commercial|ingenieur commercial)\b/.test(title);
 const pureSales = sales || /\b(ingenieur commercial|technico commercial)\b/.test(title);
 const reasons=[],alerts=[],positives=[];
 if(geo.certainty==='outside') reasons.push('Localisation hors cible');
 if(org.kind==='intermediary') reasons.push(org.reason);
 if(pureSales) reasons.push('Poste principalement commercial ou de recrutement');
 if(substantive && !relevant) reasons.push('Missions sans lien énergétique suffisamment concret');
 const published = typeof job.postedAt==='number'?job.postedAt:Date.parse(job.postedAt||'');
 const days = Number.isFinite(published) && published<=now+86400000?Math.max(0,Math.floor((now-published)/86400000)):null;
 const expired=job.availability==='expired' || (Number.isFinite(Date.parse(job.expiresAt)) && Date.parse(job.expiresAt)<now);
 if(expired) reasons.push('Offre expirée ou supprimée');
 if(days===null) alerts.push('Date de publication inconnue');
 else if(days>config.maxAgeDays) alerts.push(`Offre ancienne (${days} jours)`);
 if(!geo.eligible) alerts.push(geo.reason);
 if(!org.confirmed) alerts.push(org.reason);
 if(!substantive) alerts.push('Description insuffisante : analyse à compléter');
 if(job.availability==='unconfirmed') alerts.push('Accessibilité à revérifier');
 const categories=[];
 if(hasEnergy) categories.push('Énergie');
 if(/efficacite energetique|energy efficiency|reduction des consommations/.test(text+' '+title))categories.push('Efficacité énergétique');
 if(/performance energetique|energy performance|iso 50001|suivi des consommations/.test(text+' '+title))categories.push('Performance énergétique');
 if(/methodes|methods/.test(text+' '+title))categories.push('Méthodes');
 if(/amelioration continue|continuous improvement/.test(text+' '+title))categories.push('Amélioration continue');
 if(/performance industrielle|industrial performance|procedes|process optimization/.test(text+' '+title))categories.push('Performance industrielle');
 const w=config.weights;
 const parts={domain:Math.round(w.domain*(relevant?(specific?1:0.75):hasEnergy?0.3:0)),missions:Math.round(w.missions*Math.min(1,missionEvidence.length/4)),employer:org.kind==='direct'?w.employer:org.kind==='unknown'?Math.round(w.employer/4):0,location:geo.eligible?w.location:0,quality:Math.round(w.quality*((substantive?0.3:0)+(description.length>=600?0.2:0)+(technical?0.2:0)+(/projet|responsab|autonom|formation/.test(text)?0.2:0)+(days!==null&&days<=30?0.1:0)))};
 let score=Object.values(parts).reduce((a,b)=>a+b,0);
 const needsReview=!geo.eligible||!org.confirmed||!substantive||job.availability==='unconfirmed';
 if(needsReview)score=Math.min(score,69);
 if(reasons.length)score=0;
 if(org.kind==='direct')positives.push('Employeur final');
 if(relevant)positives.push('Missions liées à la performance énergétique');
 if(missionEvidence.length)positives.push('Analyse, optimisation ou pilotage opérationnel');
 if(geo.eligible)positives.push(geo.reason);
 if(days!==null&&days<=14)positives.push('Offre récente');
 const summary=reasons.length?`Offre rejetée : ${reasons.join(' ; ')}.`:`${category(score)} : ${positives.slice(0,3).join(', ')}. Localisation : ${geo.reason}.${needsReview?' Vérification nécessaire.':''}`;
 return {version:VERSION,score,rawScore:Object.values(parts).reduce((a,b)=>a+b,0),parts,weights:w,category:category(score,!!reasons.length),verdict:reasons.length||score<55||expired?'IGNORER':score>=70&&!needsReview?'POSTULER':'À ÉTUDIER',summary,positives,negatives:reasons,alerts,categories,geo,employer:org,evidence:{energy:energyEvidence,missions:missionEvidence},days,expired,needsReview,method:job.semantic?'Analyse IA étayée + règles':'Règles contextuelles',recommended:!needsReview&&!reasons.length&&geo.eligible&&org.kind==='direct'&&substantive&&score>=55&&(days===null||days<=config.maxAgeDays)};
}
